-- ==============================================================================
-- DailyGurus Price List - Supabase PostgreSQL Initial Schema
-- ==============================================================================

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    icon TEXT DEFAULT '',
    category_type TEXT NOT NULL CHECK (category_type IN ('veg', 'fruit')),
    display_order INT DEFAULT 0,
    active SMALLINT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. SUBCATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.subcategories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    icon TEXT DEFAULT '',
    display_order INT DEFAULT 0,
    active SMALLINT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
    subcategory_id BIGINT REFERENCES public.subcategories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    tamil_name TEXT DEFAULT '',
    image_url TEXT DEFAULT '',
    icon TEXT DEFAULT '',
    default_unit TEXT DEFAULT '',
    display_order INT DEFAULT 0,
    active SMALLINT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. PRICE DATES TABLE
CREATE TABLE IF NOT EXISTS public.price_dates (
    price_date DATE PRIMARY KEY,
    is_published SMALLINT DEFAULT 0,
    notes TEXT DEFAULT '',
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. DAILY PRICES TABLE
CREATE TABLE IF NOT EXISTS public.daily_prices (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    price_date DATE NOT NULL REFERENCES public.price_dates(price_date) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    price TEXT NOT NULL DEFAULT '',
    unit TEXT DEFAULT '',
    price_notes TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_price_date_product UNIQUE (price_date, product_id)
);

-- 6. ADMIN USERS TABLE (Optional local fallback for custom admin authentication)
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    email TEXT DEFAULT '',
    role TEXT DEFAULT 'admin',
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- INDEXES for Ultra-Fast Queries
CREATE INDEX IF NOT EXISTS idx_products_cat ON public.products(category_id, subcategory_id);
CREATE INDEX IF NOT EXISTS idx_products_active ON public.products(active, display_order);
CREATE INDEX IF NOT EXISTS idx_daily_prices_date ON public.daily_prices(price_date);
CREATE INDEX IF NOT EXISTS idx_daily_prices_prod ON public.daily_prices(product_id);
CREATE INDEX IF NOT EXISTS idx_price_dates_pub ON public.price_dates(is_published, price_date DESC);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subcategories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_dates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Categories: Public can read active categories
CREATE POLICY "Public read active categories" ON public.categories
    FOR SELECT USING (true);

-- Subcategories: Public can read active subcategories
CREATE POLICY "Public read active subcategories" ON public.subcategories
    FOR SELECT USING (true);

-- Products: Public can read active products
CREATE POLICY "Public read active products" ON public.products
    FOR SELECT USING (true);

-- Price Dates: Public can read published dates
CREATE POLICY "Public read published price dates" ON public.price_dates
    FOR SELECT USING (is_published = 1);

-- Daily Prices: Public can read prices for published dates
CREATE POLICY "Public read daily prices for published dates" ON public.daily_prices
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.price_dates
            WHERE price_dates.price_date = daily_prices.price_date
            AND price_dates.is_published = 1
        )
    );

-- Service Role / Authenticated Admins have full access
CREATE POLICY "Admin full access categories" ON public.categories
    FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');

CREATE POLICY "Admin full access subcategories" ON public.subcategories
    FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');

CREATE POLICY "Admin full access products" ON public.products
    FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');

CREATE POLICY "Admin full access price_dates" ON public.price_dates
    FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');

CREATE POLICY "Admin full access daily_prices" ON public.daily_prices
    FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');

CREATE POLICY "Admin full access admin_users" ON public.admin_users
    FOR ALL USING (auth.role() = 'authenticated' OR auth.role() = 'service_role');
